### ISSUE TITLE
SecurityException while sharing an image from the app

### ISSUE THREAD

**Issue by shyjuzz** [mrtcndnlr/Flutter-Advanced-Share#13]
E/DatabaseUtils( 9409): Writing exception to parcel
E/DatabaseUtils( 9409): java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.ilearn.learnpsc.adv_provider/cache_files/1554276419.png from pid=7007, uid=10106 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 9409): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
E/DatabaseUtils( 9409): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
E/DatabaseUtils( 9409): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:471)
E/DatabaseUtils( 9409): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:416)
E/DatabaseUtils( 9409): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
E/DatabaseUtils( 9409): 	at android.os.Binder.execTransact(Binder.java:453)

**Comment by hebrewd** [comment]
~~I faced this issue as well, adding~~
~~uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" to solve it for me.~~

No, it seems to be still happening, I am using the base64 method myself.
